openapi: 3.0.1
info:
  title: JS-REST-API
  description: 'This is a API with Users and Articles created with Express.js. You can find more about it [here](https://github.com/waterseeker/js-rest-api).'
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
tags:
- name: user
  description: Operations about user
paths:
  /api/user:
    post:
      tags:
      - user
      summary: Create a user
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Invalid payload supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: string
        login:
          type: string
        password:
          type: string
    Error:
      type: object
      properties:
        error: 
          type: string
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string