# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install backend dependencies
      run: npm ci
    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./client
    - name: Lint backend
      run: npm run lint
    - name: Lint frontend
      run: npm run lint
      working-directory: ./client
    - name: Build backend
      run: npm run build
    - name: Test backend
      run: npm test
    - name: E2E
      run: npm run test:e2e
    - name: Build frontend
      run: npm run build -- --prod
      working-directory: ./client
    - name: Test frontend
      run: npm test -- --configuration=ci
      working-directory: ./client
